# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee5be47ca114e91aed100d85c19822c3ec04447c2b822b82b847f8f6e2f46d13b465513b31f2b7622c6ef4b5eab309f2bb4e8ffb80a6787cf7ec0880012e8fa

test:
  secret_key_base: 15884542dac6d268c67441fc68c931068c1d1feb69be80d1678ab27b651632faea396a22ad6c050f513c901302344e0e889f2c5061d14961b30fcf69c5c99336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
